package springboot.dal.emailMyISAM;

import org.apache.ibatis.annotations.Mapper;
import springboot.data.request.PagingRequest;
import springboot.dto.email.EmailDto;

import java.util.List;

@Mapper
public interface EmailMyISAMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:10:47 CST 2018
     */
    int deleteByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:10:47 CST 2018
     */
    int insert(EmailMyISAMEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:10:47 CST 2018
     */
    int insertSelective(EmailMyISAMEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:10:47 CST 2018
     */
    EmailMyISAMEntity selectByPrimaryKey(Integer email_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:10:47 CST 2018
     */
    int updateByPrimaryKeySelective(EmailMyISAMEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_myisam
     *
     * @mbg.generated Thu Apr 26 00:10:47 CST 2018
     */
    int updateByPrimaryKey(EmailMyISAMEntity record);

    List<EmailDto> selectByPaging(PagingRequest request);

    Integer count();
}